### ISSUE TITLE
Make gh-pages the default branch.

### ISSUE THREAD

**Issue by jyasskin** [noncombatant/permission-delegation-api#17]
And delete the master branch. Right now, master is [9 commits ahead](https://github.com/noncombatant/permission-delegation-api/branches) of https://noncombatant.github.io/permission-delegation-api/, so you'll need to fast-forward gh-pages too.

https://help.github.com/articles/setting-the-default-branch/

**Comment by noncombatant** [comment]
I fast-forwarded gh-pages and made it the default.
