### ISSUE TITLE
Consider something other than notifications for example

### ISSUE THREAD

**Issue by benfredwells** [noncombatant/permission-delegation-api#6]
Notifications are a complicated permission, which in Chrome (other UAs?) allow push notifications to be used from service workers. I'm not sure that is a good permission to use in the example.

**Comment by noncombatant** [comment]
Push Notifications, which do use Service Workers, are distinct from Notifications, which I think do not (or, not necessarily):

https://www.w3.org/TR/permissions/#permission-registry

https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web?hl=en

https://notifications.spec.whatwg.org/
https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by noncombatant** [comment]
Regular non-Push notifications aren't complicated; clarified that that's what we mean.

**Comment by benfredwells** [comment]
In chromium AFAIK we don't have separate permissions for non-push and push notifications, and it's all confusing and needs to be sorted out. E.g. people can get push in http by asking for non-push, which then gives the single notifications permission, which then allows push.

But these are probably silly implementation details of chromium that aren't relevant for this spec.
