### ISSUE TITLE
Important permissions like webrtc aren't covered...

### ISSUE THREAD

**Issue by benfredwells** [noncombatant/permission-delegation-api#7]
... by the permissions API yet. (see https://www.w3.org/TR/permissions/#permission-registry)

**Comment by noncombatant** [comment]
Yes, but the Permissions API Registry is extensible, and hence so is the Permissions Delegation API. What should we change about this document?

**Comment by raymeskhoury** [comment]
But they are covered in the latest draft API: https://w3c.github.io/permissions/ which I hope will be published soon (I think by the time ours would be published, this would too).

**Comment by noncombatant** [comment]
I don't think we need to, or should, replicate the Registry in our spec though. I think referring to it is sufficient. Please re-open this bug if I'm missing something, though. :)

**Comment by benfredwells** [comment]
Cool, I agree this spec shouldn't redefine those, I was just worried they were so limited. If they are getting expanded then that's awesome :)
