### ISSUE TITLE
Should add a section in section 9 (other risks) for less control

### ISSUE THREAD

**Issue by benfredwells** [noncombatant/permission-delegation-api#9]
Some users want to be able to let `trustedembeddee.com` have some permissions but not `untrestedembedder.com`. This could possibly be addressed with extra UI (which is mentioned).

It would probably be good to explicitly call this out in this document as it will be a common complaint.

**Comment by noncombatant** [comment]
See what you think of this addition: https://github.com/noncombatant/permission-delegation-api/commit/dfab0bd5c0ea57689f578850733b0f169b55768c

**Comment by benfredwells** [comment]
lgtm
